import type { BaseNode, Node } from "./components/Node.svelte";
import {
	BoxesIcon,
	CircleDollarSignIcon,
	EyeIcon,
	HammerIcon,
	LayoutDashboardIcon,
	LayoutTemplateIcon,
	PaintbrushIcon,
	PillBottleIcon,
	PillIcon,
	ScanFaceIcon,
	SearchIcon,
	ShoppingCartIcon,
	UserRoundIcon,
} from "lucide-svelte";

export function generateNode(node: BaseNode, locked: boolean, level = 0): Node {
	return {
		id: node.title.toLowerCase() + crypto.getRandomValues(new Uint8Array(18)).join(""),
		title: node.title,
		points: node.points,
		days: node.days,
		team: node.team,
		icon: node.icon,
		level: level,
		locked: locked,
		children: node.children.map((child) =>
			generateNode(child, locked === true ? true : child.locked, level + 1),
		),
	};
}

export const PHARMALINK: BaseNode = {
	title: "PharmaLink",
	locked: true,
	points: 15,
	days: 7,
	team: null,
	icon: PillIcon,
	children: [
		{
			locked: true,
			title: "Login and Registration",
			points: null,
			days: 7,
			team: "Team name",
			icon: ScanFaceIcon,
			children: [
				{
					locked: true,
					title: "UI",
					points: 15,
					days: 7,
					team: "Team name",
					icon: LayoutTemplateIcon,
					children: [
						{
							locked: true,
							title: "Frontend",
							points: 15,
							days: 7,
							team: "Team name",
							icon: PaintbrushIcon,
							children: [
								{
									locked: true,
									title: "Backend",
									points: 15,
									days: 7,
									team: "Team name",
									icon: HammerIcon,
									children: [],
								},
							],
						},
					],
				},
			],
		},
		{
			locked: true,
			title: "Customer Dashboard",
			points: 15,
			days: 7,
			team: "Team name",
			icon: LayoutDashboardIcon,
			children: [
				{
					locked: true,
					title: "UI",
					points: 15,
					days: 7,
					team: "Team name",
					icon: LayoutTemplateIcon,
					children: [
						{
							locked: true,
							title: "Frontend",
							points: 15,
							days: 7,
							team: "Team name",
							icon: PaintbrushIcon,
							children: [
								{
									locked: true,
									title: "Backend",
									points: 15,
									days: 7,
									team: "Team name",
									icon: HammerIcon,
									children: [],
								},
							],
						},
					],
				},
			],
		},
		{
			locked: true,
			title: "Pharmacy Dashboard",
			points: 15,
			days: 7,
			team: "Team name",
			icon: LayoutDashboardIcon,
			children: [
				{
					locked: true,
					title: "UI",
					points: 15,
					days: 7,
					team: "Team name",
					icon: LayoutTemplateIcon,
					children: [
						{
							locked: true,
							title: "Frontend",
							points: 15,
							days: 7,
							team: "Team name",
							icon: PaintbrushIcon,
							children: [
								{
									locked: true,
									title: "Backend",
									points: 15,
									days: 7,
									team: "Team name",
									icon: HammerIcon,
									children: [
										{
											locked: true,
											title: "Pharmacy Inventory",
											points: 15,
											days: 7,
											team: "Team name",
											icon: BoxesIcon,
											children: [
												{
													locked: true,
													title: "UI",
													points: 15,
													days: 7,
													team: "Team name",
													icon: LayoutTemplateIcon,
													children: [
														{
															locked: true,
															title: "Frontend",
															points: 15,
															days: 7,
															team: "Team name",
															icon: PaintbrushIcon,
															children: [
																{
																	locked: true,
																	title: "Backend",
																	points: 15,
																	days: 7,
																	team: "Team name",
																	icon: HammerIcon,
																	children: [],
																},
															],
														},
													],
												},
											],
										},
									],
								},
							],
						},
					],
				},
			],
		},
		{
			locked: true,
			title: "Medicine Details",
			points: 15,
			days: 7,
			team: "Team name",
			icon: EyeIcon,
			children: [
				{
					locked: true,
					title: "UI",
					points: 15,
					days: 7,
					team: "Team name",
					icon: LayoutTemplateIcon,
					children: [
						{
							locked: true,
							title: "Frontend",
							points: 15,
							days: 7,
							team: "Team name",
							icon: PaintbrushIcon,
							children: [
								{
									locked: true,
									title: "Backend",
									points: 15,
									days: 7,
									team: "Team name",
									icon: HammerIcon,
									children: [],
								},
							],
						},
					],
				},
			],
		},
		{
			locked: true,
			title: "Find Medicine",
			points: 15,
			days: 7,
			team: "Team name",
			icon: SearchIcon,
			children: [
				{
					locked: true,
					title: "UI",
					points: 15,
					days: 7,
					team: "Team name",
					icon: LayoutTemplateIcon,
					children: [
						{
							locked: true,
							title: "Frontend",
							points: 15,
							days: 7,
							team: "Team name",
							icon: PaintbrushIcon,
							children: [
								{
									locked: true,
									title: "Backend",
									points: 15,
									days: 7,
									team: "Team name",
									icon: HammerIcon,
									children: [
										{
											locked: true,
											title: "Cart",
											points: 15,
											days: 7,
											team: "Team name",
											icon: ShoppingCartIcon,
											children: [
												{
													locked: true,
													title: "UI",
													points: 15,
													days: 7,
													team: "Team name",
													icon: LayoutTemplateIcon,
													children: [
														{
															locked: true,
															title: "Frontend",
															points: 15,
															days: 7,
															team: "Team name",
															icon: PaintbrushIcon,
															children: [
																{
																	locked: true,
																	title: "Backend",
																	points: 15,
																	days: 7,
																	team: "Team name",
																	icon: HammerIcon,
																	children: [],
																},
															],
														},
													],
												},
											],
										},
										{
											locked: true,
											title: "Place Order",
											points: 15,
											days: 7,
											team: "Team name",
											icon: CircleDollarSignIcon,
											children: [
												{
													locked: true,
													title: "UI",
													points: 15,
													days: 7,
													team: "Team name",
													icon: LayoutTemplateIcon,
													children: [
														{
															locked: true,
															title: "Frontend",
															points: 15,
															days: 7,
															team: "Team name",
															icon: PaintbrushIcon,
															children: [
																{
																	locked: true,
																	title: "Backend",
																	points: 15,
																	days: 7,
																	team: "Team name",
																	icon: HammerIcon,
																	children: [],
																},
															],
														},
													],
												},
											],
										},
									],
								},
							],
						},
					],
				},
			],
		},
		{
			locked: true,
			title: "Pharmacy Profile",
			points: 15,
			days: 7,
			team: "Team name",
			icon: PillBottleIcon,
			children: [
				{
					locked: true,
					title: "UI",
					points: 15,
					days: 7,
					team: "Team name",
					icon: LayoutTemplateIcon,
					children: [
						{
							locked: true,
							title: "Frontend",
							points: 15,
							days: 7,
							team: "Team name",
							icon: PaintbrushIcon,
							children: [
								{
									locked: true,
									title: "Backend",
									points: 15,
									days: 7,
									team: "Team name",
									icon: HammerIcon,
									children: [],
								},
							],
						},
					],
				},
			],
		},
		{
			locked: true,
			title: "Customer Profile",
			points: 15,
			days: 7,
			team: "Team name",
			icon: UserRoundIcon,
			children: [
				{
					locked: true,
					title: "UI",
					points: 15,
					days: 7,
					team: "Team name",
					icon: LayoutTemplateIcon,
					children: [
						{
							locked: true,
							title: "Frontend",
							points: 15,
							days: 7,
							team: "Team name",
							icon: PaintbrushIcon,
							children: [
								{
									locked: true,
									title: "Backend",
									points: 15,
									days: 7,
									team: "Team name",
									icon: HammerIcon,
									children: [],
								},
							],
						},
					],
				},
			],
		},
	],
};
